### ISSUE TITLE
suggestion: count maps as currency as well

### ISSUE THREAD

**Issue by Xloctis** [viktorgullmark/exilence#105]
assuming price on poe.ninja maps can be counted as well

**Comment by projectsix84** [comment]
+1 on this. I use a dump tab and like to keep track of my profit/loss over X amount of maps. Like, running 30 elder UGS maps and knowing what my cost was and then having Exilence figure out the net worth of stuff dropped by only selecting that tab for it to count so I know how much I made. When it doesn't count map drops, I can't do that since those are a huge part of it.

Thanks for the great program!

**Comment by projectsix84** [comment]
> My understanding from past comments from Author, and authors of other programs, is that the POE API does not pull Map Stash Tabs.
> 
> I just posted in the last Reddit thread, that a potential workaround could be to use the Publish Stash Tab API instead for Map Tabs.
> 
> E.g. if people want their Map Tabs to be used, they would need to make them public, and then that API which is currently used by the trade sites, can be used to pull down the Maps. Alternatively we can just pray that GGG add it to the API

Fair enough, but it doesn't seem to count maps in any tab. I use a 'dump' tab of loot from the maps I run and I was putting maps into there. It wasn't counting those. So it's not just a map tab issue.

**Comment by viktorgullmark** [comment]
@projectsix84 This is now fixed and will be live in the next release. However, we can't price the map-tab yet, but dump-tabs will work. Keeping the issue open until it's publised.

**Comment by projectsix84** [comment]
> @projectsix84 This is now fixed and will be live in the next release. However, we can't price the map-tab yet, but dump-tabs will work. Keeping the issue open until it's published.

Awesome, thank you! Keep up the good work. That was the only issue I had with it.
