### ISSUE TITLE
Login and disconnection problems

### ISSUE THREAD

**Issue by Freakey1** [viktorgullmark/exilence#122]
I have two problems: Everytime I want to login, I can only login using "Change my login settings" and putting all the info again (including reentering my POESession ID (even tho its the same code) and the path to Client.txt). Just hitting "Log me in" or using "Change my login settings" with the already saved info never works, it stays "logging in" forever. Second, Exilence stops tracking and updating my networth and Chaos per hour after a few minutes using it and/or disconnects from PoE site. It's already set as an exception in Windows Firewall and I'm running it as administrator for no effect in this matter.

**Comment by ghord** [comment]
Same issue here. Every time I launch the application the logging in does not work. Additionally, If I close Exlience during this time, I have to fill in all my details again.

**Comment by viktorgullmark** [comment]
Thanks for the report. I will take a look at this when I have time.

I replicated this locally by dying on a character that I had logged in with, the next time I restarted Exilence this happened, since the login-settings were invalid due to my character not existing anymore. 
However, the settings should be overridden once you successfully login, so I don't see this happening multiple times..

Can you post screenshots of your settings here? Without modifying anything, just show me how they look upon startup (preferebly every step, but character/league should be enough).

**Comment by ghord** [comment]
I've just done clean install of the application on another pc, and I'm having the same issue:

Steps to reproduce:
1. Fill in login settings in the stepper (choose server/league/account/possid etc)
2. App sees my character data and everything is ok
3. Close application
4. Open application again. Following screen shows up:

![obraz](https://user-images.githubusercontent.com/10825459/51251816-792a8b00-199a-11e9-978f-12b433539edc.png)

5. Click "Log me in"
6. Progress bar spins without effect like on screenshot
7. Nothing happens so I close the app with "X"
8. After opening application again, there is no Welcome back message it just takes me straight to initial configuration stepper. Looks like settings got reset/corrupted.

**Comment by ghord** [comment]
I unchecked "Hide Characters tab" in my pathofexile.com settings and now it works without the issue. Seems to be connected to this settings.

**Comment by viktorgullmark** [comment]
Thanks a lot for the information @ghord. As you confirmed it seems related to this setting. We'll highlight this in one of the steps in a future release, and possibly handle the error if it happens.

Thanks for the heads up.
