### ISSUE TITLE
net worth fluctuating by several hundred every few minutes

### ISSUE THREAD

**Issue by jnitis** [viktorgullmark/exilence#130]
As of a few days ago the net worth of my character is fluctuating dramatically every few minutes by 300-400 or so.  I'm not sure what's causing it, nothing is moving in market value back and forth that much that I can think of.  Prior to a few days ago this never occurred.

![image](https://user-images.githubusercontent.com/5638068/51438120-6ac7c200-1c6d-11e9-88bb-4d24cf562662.png)

**Comment by viktorgullmark** [comment]
Thanks for the issue. Can you check if theres a difference in items between two snapshots? 

If you go to "current group", then select yourself and press "currency", you should be able to click on specific points in the graph to load the value and items associated with it.

**Comment by viktorgullmark** [comment]
Also, what league is this, and is the maptab selected?

**Comment by jnitis** [comment]
Thanks for the speedy reply.

I checked several points in time by clicking on the graph and I can't nail down anything specific.  There's certainly no item changing 400-500c in value as I'd see it at the top of the list.

This is betrayal league with map tab selected.  I have unselected the map tab for now to see how that impacts things.  BTW I do not have low confidence pricing enabled.

Cheers

**Comment by sjaanus** [comment]
@viktorgullmark Could it be related to maps not being registered? I had some sudden drops and when I checked the 24h log, it showed that I had lost all my maps. They came back after couple of minutes.

**Comment by viktorgullmark** [comment]
@jnitis Another question for you; do you use the official trade-site? (pathofexile.com/trade)

**Comment by jnitis** [comment]
Hi!  I haven't had a chance to check anything extra in detail but your recent messages regarding using the official trade website, that's gotta be it!  Last few days I've had trouble running searches with the dreaded red box at the bottom of the page saying can't load next results.  Looked it up, apparently it's a rate limiter message and I was puzzled because I wasn't doing searches that quickly. :-) A-ha!

As for 429, which console would that be in, the game client or elsewhere?

Cheers, great find.  I have hundreds of maps, must be related.

**Comment by viktorgullmark** [comment]
@jnitis Thanks for the info. The 429 is certainly there then, it's in the console in Exilence (windowsbutton + shift + i, then press "console" in the top-right). 

The problem here is that you use the official trade-site, since we use it as well to fetch data for the map-tab. We will have to add some margin to our fetching function, to allow browsing the site at the same time.

429 means that you've been ratelimited (same error as you see in red on pathofexile.com/trade)

Thanks for the information, will look deeper into this. For now, if you want accurate pricing, discontinue use of the official trade-site, at least if you can predict an update in Exilence will happen (4-5 minutes passed).

**Comment by viktorgullmark** [comment]
@jnitis Sorry for the spam, but do you want a private release to test this out since you have many maps? I could send you an upload link if you don't mind.

**Comment by viktorgullmark** [comment]
Actually I just released this in 0.9.13. Update your Exilence to see if it resolves this issue, and let us know here if it doesn't. Closing it for now!
