### ISSUE TITLE
pathofexile.com could not be reached all of the time

### ISSUE THREAD

**Issue by gotex007** [viktorgullmark/exilence#186]
Today is the first time I've used this application and I get this damn error constantly. It wouldn't be nearly as bad if it didn't create a prompt for each and every time it happens so after an hour of farming I go to look and have to click "okay" 20 times.

[Screenshot of the error I'm talking about](https://i.imgur.com/zELH7qE.png)

**Comment by viktorgullmark** [comment]
Thanks for the report. This should only be shown once, so this is for sure a bug.

**Comment by gotex007** [comment]
It's still pretty bad just how frequently it fails to reach pathofexile.com though. What does offline-mode even do? And what is low confidence pricing? I wish there were some explanations in the client for this stuff.

**Comment by viktorgullmark** [comment]
That is surely on pathofexile.com's end. This is not a frequent occurence as a whole, but probably happened because of the migrations or preparations for Synthesis. The site is usually very unstable at or around league-start. 

Offline-mode allows you to keep using Exilence without being kicked out of the app. We rely on pathofexile.com to be up, but if it goes down, we still let you play without gear/net worth updates, and automatically reconnect you when the site is back up.

Low-confidence pricing includes items which prices are not confident enough to be displayed on poe.ninja, similar to the checkbox over at https://poe.ninja (you can test it yourself). In detail, on our end we include all items with at least 10 listings, but with low confidence pricing on, we include everything.

**Comment by viktorgullmark** [comment]
Fixed with https://github.com/viktorgullmark/exilence/commit/5f9c6e905d20807cfcb901e686265533006a7e95
