### ISSUE TITLE
Value of items is severely off.

### ISSUE THREAD

**Issue by gotex007** [viktorgullmark/exilence#187]
It tried telling me a white map (was like a T4) was worth 20c earlier so i turned off map pricing.

But it does this all the time. It seems really weird just how off the pricing is.

It also shows a min/max/mode/median/average right? Most of my items shows all 0s. Some items like [GCPs](https://i.imgur.com/qawi5C1.png) it values outside of the range entirely for some reason.

I know this tool is in beta, but I'm hoping some of these issues I'm experiencing can be fixed up quickly because I really like the concept of the tool.

**Comment by viktorgullmark** [comment]
The listed price is from https://poe.ninja, while the prices that appear when you hover are from https://poe.watch. We should add the ninja-value to the tooltip to get it accurate.

If prices are off, it's a problem on poe.ninja's end, since we fetch all of our prices directly from there. Price-hickups is a known bug though, and we've been in contact with him regarding it, and we have a plan to working around it. 

See https://github.com/viktorgullmark/exilence/issues/179 and https://github.com/viktorgullmark/exilence/issues/188

Thanks for your report, closing.
