### ISSUE TITLE
gain per map/area always displaying "-"

### ISSUE THREAD

**Issue by Davst** [viktorgullmark/exilence#227]
This feature seems to be broken currently. all areas display "-"

**Comment by sclient** [comment]
Came here looking for help on the same issue. Tried full clearing all my settings to no avail. Current released version 0.9.34 Beta. Windows 8.1.

**Comment by viktorgullmark** [comment]
A fix is not being implemented for this currently as we're focusing on Exilence Next. We will post news regarding this in a few days in our Discord.

**Comment by sclient** [comment]
So, this is a pretty big bug, and it has been present for a pretty long while now. I hope there is a decent ETA on a stable version of next, otherwise I really think this bug should just be fixed. Are we really expected to wait weeks or months from now for next to be stable?

**Comment by viktorgullmark** [comment]
We are fully aware. We just don't have this bug as a priority right now. Both me and Umo work full time jobs and are very limited in our free time at the moment. Because of this we don't always have time to publish new versions. Right now our main focus is getting Exilence Next out asap, any time we spend on other bugs will delay it as we are only two people developing.

Also, anyone is free to contribute with pull requests if they have skills in Angular.
