### ISSUE TITLE
Incubators not tracking in Net Worth

### ISSUE THREAD

**Issue by projectsix84** [viktorgullmark/exilence#238]
Hey, I'm using Exilence to track my dump tab while farming. Love the tool.

I've noticed that it doesn't seem to be tracking incubators, though. None of them show on the loot list under the net worth tab. I have 13 of them in there at the moment.

I didn't see this in the known issues list.. any idea what's up?

One other issue I am having.. I am not sure if it's connected to the above issue at all, but thought I would mention it..  if I turn off 'Map pricing' in the net worth settings to not include maps, it breaks the net worth altogether. It shows zero loot. I have automatic price updates on. Low confidence, character-specific pricing and inventory pricing are off. It's also set to include all items for theshhold (no minimum).

Hope that info helps.

Thanks!

**Comment by viktorgullmark** [comment]
Thanks for the post. Most of these issues are known and are being taken into consideration into Exilence Next. We've paused the development of both projects for now since both me and Umocrajen are very occupied, but we'll try to get E Next going as soon as possible and make sure these issues are not a problem there.
