### ISSUE TITLE
[Bug] Armourer's Scrap with iffy amout.

### ISSUE THREAD

**Issue by hfok** [viktorgullmark/exilence#43]
One of my mate in the group has very high value on his Armourer's Scrap (see pic) while everyone else have the standard, according to poe.ninja price

pic:  https://i.imgur.com/rIWmVrB.png

**Comment by viktorgullmark** [comment]
Hey. We fetch all our prices directly from https://poe.ninja. We had several reports about this, and turns out it was a temporary hickup on his end, not sure what caused it. I also noticed that some page-loads it was fine, while other times it showed a high chaosEquivalent value. Either way this was on his end, so I'll close this. 

Thanks for the report nonetheless!
