### ISSUE TITLE
Add setting to mask group name between restarts

### ISSUE THREAD

**Issue by petterannerwall** [viktorgullmark/exilence#77]

**Comment by viktorgullmark** [comment]
This has been added now. However, since we don't have a masked property on the party-interface, we can't tie it to a specific group permanently. 

This means that if you mask your group -> restart -> go to dashboard, the field will be masked, but the group won't be masked in the list of recent groups. Realistically this is not a problem since we generate a new code each time we start the app, but should still be mentioned.
